---
- name: install
  ansible.builtin.apt:
    cache_valid_time: 86400
    name: "{{ item }}"
    state: present
  with_items:
    - ganglia-monitor
    - ganglia-monitor-python
    - ganglia-modules-linux

- name: modpython fix
  block:
    - name: libpython2.7
      ansible.builtin.apt:
        cache_valid_time: 86400
        name: libpython2.7
        state: present
    - name: modpython.so
      ansible.builtin.copy:
        dest: /usr/lib/ganglia/modpython.so
        group: root
        mode: 0755
        owner: root
        src: modpython.so
      notify:
        - Restart gmond service
  when:
    - ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

- name: gmond systemd
  ansible.builtin.copy:
    dest: /etc/systemd/system/ganglia-monitor.service
    group: root
    mode: 0644
    owner: root
    src: ganglia-monitor.service
  notify:
    - Systemd daemon reload
    - Restart gmond service
